// Mismo backend de SEC. No se ejecuta ningún cambio hasta iniciar sesión.
const API='https://sec-backend-gg4j.onrender.com/distribucion';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let usuario=null,token=sessionStorage.getItem('sec-distribucion-token')||'',conductores=[],vehiculos=[],repartos=[],pedidos=[],mapa=null;
const secciones=[['Conductores','Alta, modificación y baja de conductores.'],['Mapa de clientes','Comercios del plan de entregas.'],['Visitas y recorridos','Registro y recreación del recorrido del conductor.'],['Supervisor','Control del plan de entregas.'],['Reemplazos de ruta','Reemplazar al conductor de un reparto.'],['Alertas','Faltantes de ubicación y asignación.'],['Auditoría','Historial de cambios del módulo.'],['Importar pedidos','Excel de distribución.'],['Vehículos','Internos y patentes; camión o tractor con semi.'],['App Conductor','Entregas, incidencias, fotos y GPS con la página abierta.']];
function mensaje(s){$('#mensaje').textContent=s;}
async function api(path,options={}){const h={Authorization:'Bearer '+token,...options.headers};if(options.body&&!(options.body instanceof FormData))h['Content-Type']='application/json';const r=await fetch(API+path,{...options,headers:h});let d;try{d=await r.json();}catch{throw Error('El servidor todavía no tiene instalado el módulo Distribución o devolvió una respuesta inválida');}if(!r.ok)throw Error(d.error||'Error del servidor');return d;}
function run(fn){return async()=>{mensaje('');try{await fn();}catch(e){mensaje(e.message);}};}
function login(){token='';sessionStorage.removeItem('sec-distribucion-token');$('#nav').innerHTML='<a href="../index.html">Comercial</a>';$('#vista').innerHTML=`<div class="panel"><h2>Ingreso a Distribución</h2><form id="login"><label>Empresa<input name="empresa" value="rebesa" required autocomplete="organization"></label><label>Legajo<input name="legajo" required autocomplete="username"></label><label>Contraseña<input name="clave" type="password" required autocomplete="current-password"></label><button>Ingresar</button></form><details><summary>Inicialización del módulo — primera instalación</summary><p>Usar sólo después de ejecutar la migración en el servidor.</p><form id="init"><label>Clave de inicialización del servidor<input name="bootstrap" type="password" required></label><label>Empresa<input name="empresa" value="rebesa" required></label><label>Legajo administrador<input name="legajo" required maxlength="20"></label><label>Nombre<input name="nombre" required></label><label>Apellido<input name="apellido" required></label><label>Contraseña nueva<input name="clave" type="password" minlength="8" required></label><button>Crear primer administrador</button></form></details></div>`;
 $('#login').onsubmit=e=>{e.preventDefault();run(async()=>{const b=Object.fromEntries(new FormData(e.target));const d=await api('/login',{method:'POST',body:JSON.stringify(b)});token=d.token;usuario=d.usuario;sessionStorage.setItem('sec-distribucion-token',token);await inicio();})()};
 $('#init').onsubmit=e=>{e.preventDefault();run(async()=>{const b=Object.fromEntries(new FormData(e.target));const secret=b.bootstrap;delete b.bootstrap;await api('/inicializar',{method:'POST',headers:{Authorization:'Bearer '+secret},body:JSON.stringify(b)});e.target.reset();mensaje('Administrador creado. Ingresá arriba con su legajo y contraseña.');})()};
}
async function menuAdministrador(){if(mapa){mapa.remove();mapa=null;}$('#nav').innerHTML='<a href="../index.html">Comercial</a><button id="home">Distribución</button><button id="salir">Cerrar sesión</button>';$('#home').onclick=run(inicio);$('#salir').onclick=run(async()=>{detenerGps();await api('/logout',{method:'POST'});sessionStorage.removeItem('sec-dist-apk-gps');if(window.SECAndroid){localStorage.removeItem('vendedorId');sessionStorage.removeItem('sec-distribucion-token');location.href='salida/login-vendedor.html';return;}login();});$('#vista').innerHTML=`<h2>Distribución</h2><div class="menu-principal">${secciones.map(([p,desc],i)=>`<button class="menu-card" data-section="${i}"><h3>${esc(p)}</h3><p>${esc(desc)}</p></button>`).filter((_,i)=>usuario?.rol!=='CONDUCTOR'||[1,2,9].includes(i)).join('')}</div>`;document.querySelectorAll('[data-section]').forEach(b=>b.onclick=run(()=>abrir(secciones[+b.dataset.section][0])));}
function tabla(head,rows){return `<div class="panel"><table><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table>${rows.length?'':'<p>No hay registros.</p>'}</div>`;}
async function abrir(p){if(mapa){mapa.remove();mapa=null;}mensaje('');$('#vista').innerHTML='<h2>'+esc(p)+'</h2>';
 if(p==='Conductores'){conductores=await api('/conductores');abm();return;}
 if(p==='Auditoría'){const rows=await api('/auditoria');$('#vista').innerHTML+=tabla(['Fecha','Usuario','Acción','Detalle'],rows.map(r=>[esc(new Date(r.fecha).toLocaleString('es-AR')),esc((r.nombre||'')+' '+(r.apellido||'')),esc(r.accion),esc(JSON.stringify(r.detalle))]));return;}
 if(['Importar pedidos','Vehículos'].includes(p)){const isV=p==='Vehículos';$('#vista').innerHTML+=`<div class="panel"><p>${isV?'Columnas: INTERNO, PATENTE, TIPO (camion, tractor, semi).':'COD_CLI vincula el cliente de SEC. ANULADO y ESTADO se ignoran. Los días son los de FECHAENTREGA.'}</p><input id="archivo" type="file" accept=".xlsx,.xls,.csv"><button id="importar">Importar</button></div>`;$('#importar').onclick=run(async()=>{const f=$('#archivo').files[0];if(!f)throw Error('Seleccionar archivo');const form=new FormData();form.append('archivo',f);const d=await api(isV?'/vehiculos/importar':'/importar',{method:'POST',body:form});mensaje('Importados: '+d.importados);});if(isV){vehiculos=await api('/vehiculos');$('#vista').innerHTML+=tabla(['Interno','Patente','Tipo'],vehiculos.map(v=>[esc(v.interno),esc(v.patente),esc(v.tipo)]));}return;}
 if(p==='Visitas y recorridos'){await recorridos();return;}
 if(p==='App Conductor'){await conductor();return;}
 pedidos=await api('/pedidos');repartos=await api('/repartos');
 if(p==='Mapa de clientes'){$('#vista').innerHTML+=`<div class="panel"><label>Fecha<input id="fecha" type="date"></label><label>Despacho<select id="despacho"><option value="">Todos</option>${repartos.map(r=>`<option value="${esc(r.id)}">${esc(r.fecha.slice(0,10)+' · '+r.despacho)}</option>`).join('')}</select></label><div id="mapa"></div><p id="sincoordenadas"></p></div>`;const draw=()=>{if(mapa)mapa.remove();if(!window.L){mensaje('No se pudo cargar el componente de mapa');return;}mapa=L.map('mapa').setView([-34.65,-58.8],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(mapa);const seen=new Set(),pts=[],rs=pedidos.filter(p=>(!$('#fecha').value||p.fecha.slice(0,10)===$('#fecha').value)&&(!$('#despacho').value||p.reparto_id===$('#despacho').value));let missing=0;for(const p of rs){if(seen.has(p.codigo_cliente))continue;seen.add(p.codigo_cliente);if(p.latitud==null||p.longitud==null){missing++;continue;}const lat=Number(p.latitud),lng=Number(p.longitud);if(!Number.isFinite(lat)||!Number.isFinite(lng)){missing++;continue;}L.marker([lat,lng]).addTo(mapa).bindPopup(esc(p.codigo_cliente+' · '+p.nombre_cliente));pts.push([lat,lng]);}if(pts.length)mapa.fitBounds(pts,{padding:[25,25],maxZoom:16});$('#sincoordenadas').textContent='Clientes sin coordenadas: '+missing;};$('#fecha').onchange=draw;$('#despacho').onchange=draw;draw();return;}
 if(p==='Alertas'){$('#vista').innerHTML+=tabla(['Referencia','Motivo'],repartos.filter(r=>!r.conductor_id||!r.principal_id).map(r=>[esc(r.despacho),esc(!r.conductor_id?'Sin conductor asignado':'Sin vehículo asignado')]).concat(pedidos.filter(p=>p.latitud==null||p.longitud==null).map(p=>[esc(p.codigo_cliente),'Cliente sin coordenadas o sin vínculo de empresa'])));return;}
 $('#vista').innerHTML+=tabla(['Fecha','Despacho','Conductor','Interno / patente','Semi','Acción'],repartos.map(r=>[esc(r.fecha.slice(0,10)),esc(r.despacho),esc(r.conductor||r.conductor_nombre||'Sin asignar'),esc((r.interno||'')+' / '+(r.patente||'')),esc((r.interno_semi||'')+' / '+(r.patente_semi||'')),`<button data-reparto="${esc(r.id)}">Asignar / reemplazar</button>`]));document.querySelectorAll('[data-reparto]').forEach(b=>b.onclick=run(()=>asignar(b.dataset.reparto)));
}
function abm(id){const c=conductores.find(c=>c.id===id)||{};$('#vista').innerHTML=`<h2>Conductores</h2><div class="panel"><form id="abm"><label>Legajo<input name="legajo" required maxlength="20" value="${esc(c.legajo||'')}"></label><label>Nombre<input name="nombre" required value="${esc(c.nombre||'')}"></label><label>Apellido<input name="apellido" required value="${esc(c.apellido||'')}"></label><label>Teléfono<input name="telefono" type="tel" value="${esc(c.telefono||'')}"></label><label>${id?'Nueva contraseña (vacío conserva la actual)':'Contraseña'}<input name="clave" type="password" minlength="8" ${id?'':'required'}></label><label>Estado<select name="activo"><option value="true" ${c.activo!==false?'selected':''}>Activo</option><option value="false" ${c.activo===false?'selected':''}>Inactivo</option></select></label><button>Guardar</button><button type="button" id="nuevo">Nuevo</button></form></div>`+tabla(['Legajo','Nombre','Estado','Acción'],conductores.map(c=>[esc(c.legajo),esc(c.nombre+' '+c.apellido),c.activo?'Activo':'Inactivo',`<button data-edit="${esc(c.id)}">Editar / baja</button>`]));$('#nuevo').onclick=()=>abm();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>abm(b.dataset.edit));$('#abm').onsubmit=e=>{e.preventDefault();run(async()=>{const b=Object.fromEntries(new FormData(e.target));b.activo=b.activo==='true';await api('/conductores'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(b)});await abrir('Conductores');mensaje('Conductor guardado en SEC.');})()};}
async function asignar(id){conductores=await api('/conductores');vehiculos=await api('/vehiculos');const r=repartos.find(r=>r.id===id);const opt=(rs,val,field)=>'<option value="">Sin asignar</option>'+rs.map(v=>`<option value="${esc(v.id)}" ${v.id===val?'selected':''}>${esc(field(v))}</option>`).join('');$('#vista').innerHTML=`<h2>Asignar / reemplazar · ${esc(r.despacho)}</h2><div class="panel"><form id="asignar"><label>Conductor<select name="conductor_id">${opt(conductores.filter(c=>c.activo),r.conductor_id,c=>c.legajo+' · '+c.nombre+' '+c.apellido)}</select></label><label>Camión / tractor<select name="principal_id">${opt(vehiculos.filter(v=>v.activo&&v.tipo!=='semi'),r.principal_id,v=>v.interno+' · '+v.patente)}</select></label><label>Semi<select name="semi_id">${opt(vehiculos.filter(v=>v.activo&&v.tipo==='semi'),r.semi_id,v=>v.interno+' · '+v.patente)}</select></label><button>Guardar</button></form></div>`;$('#asignar').onsubmit=e=>{e.preventDefault();run(async()=>{await api('/repartos/'+id,{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});await abrir('Reemplazos de ruta');mensaje('Asignación guardada y auditada.');})()};}
// El token se conserva sólo durante la sesión del navegador.
if(token)run(async()=>{usuario=await api('/me');await inicio();if(window.SECAndroid&&usuario.rol==='CONDUCTOR'&&sessionStorage.getItem('sec-dist-apk-gps'))await abrir('App Conductor');})();else login();

let gpsWatch=null;
function fechaHoy(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
async function conductor(){
 if(usuario?.rol!=='CONDUCTOR'){mensaje('Ingresá con el usuario del conductor para registrar su recorrido.');return;}
 const fecha=fechaHoy(),ps=await api('/pedidos?fecha='+fecha),vs=await api('/visitas?fecha='+fecha),seen=new Set();
 $('#vista').innerHTML+=`<div class="panel"><p>En la APK de SEC se aprovecha el GPS existente, incluso con pantalla bloqueada. En navegador se registra mientras la página está abierta. El recorrido se vincula a tu sesión de Distribución.</p><button id="gpsin">Iniciar recorrido</button><button id="gpsout">Detener recorrido</button><p id="gpsestado"></p></div>`;
 $('#gpsin').onclick=()=>{if(gpsWatch!==null)return;if(window.SECAndroid&&!sessionStorage.getItem('sec-dist-apk-gps')){run(async()=>{const d=await api('/gps-apk/iniciar',{method:'POST'});localStorage.setItem('vendedorId',d.clave);sessionStorage.setItem('sec-dist-apk-gps','1');location.reload();})();return;}if(!navigator.geolocation){mensaje('El dispositivo no dispone de ubicación.');return;}gpsWatch=navigator.geolocation.watchPosition(pos=>{api('/gps',{method:'POST',body:JSON.stringify({conductor_id:usuario.id,latitud:pos.coords.latitude,longitud:pos.coords.longitude,precision_metros:pos.coords.accuracy,velocidad:pos.coords.speed,fecha_local:new Date(pos.timestamp).toISOString()})}).then(()=>{$('#gpsestado')&&($('#gpsestado').textContent='Último punto enviado: '+new Date(pos.timestamp).toLocaleTimeString());}).catch(e=>mensaje('GPS: '+e.message));},e=>mensaje('Ubicación: '+e.message),{enableHighAccuracy:true,maximumAge:0,timeout:20000});};
 $('#gpsout').onclick=run(async()=>{detenerGps();await api('/gps-apk/detener',{method:'POST'});if(window.SECAndroid){sessionStorage.removeItem('sec-dist-apk-gps');localStorage.removeItem('vendedorId');location.href='salida/login-vendedor.html';}});
 if(window.SECAndroid&&sessionStorage.getItem('sec-dist-apk-gps'))$('#gpsin').onclick();
 const stops=ps.filter(p=>{const key=p.reparto_id+'|'+p.codigo_cliente;if(seen.has(key))return false;seen.add(key);return true;});
 $('#vista').innerHTML+=tabla(['Cliente','Despacho','Resultado','Acción'],stops.map((p,i)=>{const v=vs.find(v=>v.reparto_id===p.reparto_id&&v.codigo_cliente===p.codigo_cliente);return [esc(p.codigo_cliente+' · '+p.nombre_cliente),esc(p.despacho),esc(v?.estado||'Pendiente'),`<button data-stop="${i}">Registrar entrega / foto</button>`];}));
 document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=run(()=>resultado(stops[+b.dataset.stop])));
}
function detenerGps(){if(gpsWatch!==null)navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null;if($('#gpsestado'))$('#gpsestado').textContent='Recorrido detenido.';}
async function resultado(p){$('#vista').innerHTML=`<h2>${esc(p.codigo_cliente+' · '+p.nombre_cliente)}</h2><div class="panel"><form id="resultado"><label>Resultado<select name="estado"><option>ENTREGADO</option><option>CERRADO</option><option>INCIDENCIA</option><option>VISITADO</option></select></label><label>Observación<textarea name="observacion" maxlength="3000"></textarea></label><label>Foto opcional (JPEG / PNG, hasta 5 MB)<input id="foto" type="file" accept="image/jpeg,image/png" capture="environment"></label><button>Guardar</button></form></div>`;$('#resultado').onsubmit=e=>{e.preventDefault();run(async()=>{const file=$('#foto').files[0];if(file&&file.size>5*1024*1024)throw Error('La foto supera 5 MB');const v=await api('/visitas',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(e.target)),reparto_id:p.reparto_id,codigo_cliente:p.codigo_cliente})});if(file){const f=new FormData();f.append('archivo',file);try{await api('/visitas/'+v.id+'/foto',{method:'POST',body:f});}catch(err){throw Error('Resultado guardado; la foto no se guardó: '+err.message);}}await abrir('App Conductor');mensaje('Resultado guardado.');})();};}
async function recorridos(){
 const cs=usuario?.rol==='CONDUCTOR'?[]:await api('/conductores');$('#vista').innerHTML+=`<div class="panel"><label>Fecha<input id="recfecha" type="date" value="${fechaHoy()}"></label>${cs.length?`<label>Conductor<select id="recconductor">${cs.map(c=>`<option value="${esc(c.id)}">${esc(c.nombre+' '+c.apellido)}</option>`).join('')}</select></label>`:''}<button id="cargarrec">Ver recorrido</button><p id="recinfo"></p><div id="mapa"></div><label>Recrear posición<input id="replay" type="range" min="0" max="0" value="0"></label><p id="hora"></p><div id="visitaslista"></div></div>`;
 $('#cargarrec').onclick=run(async()=>{const f=$('#recfecha').value;if(!f)throw Error('Seleccionar fecha');const id=$('#recconductor')?.value;const puntos=await api('/gps?fecha='+f+(id?'&conductor_id='+encodeURIComponent(id):''));let visitas=await api('/visitas?fecha='+f);if(id)visitas=visitas.filter(v=>v.conductor_id===id);$('#visitaslista').innerHTML=tabla(['Cliente','Resultado','Llegada','Permanencia registrada','Fotos'],visitas.map(v=>[esc(v.codigo_cliente+' · '+v.nombre_cliente),esc(v.estado),esc(new Date(v.llegada).toLocaleString('es-AR')),esc(Math.round(Number(v.permanencia_segundos)/60)+' min'),`<button data-fotos="${esc(v.id)}">Ver fotos</button>`]));document.querySelectorAll('[data-fotos]').forEach(b=>b.onclick=run(async()=>{const fs=await api('/visitas/'+b.dataset.fotos+'/fotos');for(const f of fs){const r=await fetch(API+'/fotos/'+f.id,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('No se pudo cargar la foto');const url=URL.createObjectURL(await r.blob()),img=document.createElement('img');img.src=url;img.style.maxWidth='100%';img.onload=()=>URL.revokeObjectURL(url);b.parentNode.appendChild(img);}if(!fs.length)mensaje('Esta visita no tiene fotos.');b.disabled=true;}));
 $('#recinfo').textContent=puntos.length+' puntos registrados. Los saltos mayores a 5 minutos se muestran como tramos separados.';if(mapa)mapa.remove();if(!window.L)throw Error('No se pudo cargar el mapa');mapa=L.map('mapa').setView([-34.65,-58.8],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(mapa);let tramo=[];for(let i=0;i<puntos.length;i++){if(i&&new Date(puntos[i].fecha)-new Date(puntos[i-1].fecha)>300000){L.polyline(tramo).addTo(mapa);tramo=[];}tramo.push([Number(puntos[i].latitud),Number(puntos[i].longitud)]);}if(tramo.length)L.polyline(tramo).addTo(mapa);if(puntos.length){mapa.fitBounds(puntos.map(p=>[Number(p.latitud),Number(p.longitud)]),{maxZoom:16,padding:[20,20]});const marker=L.marker([puntos[0].latitud,puntos[0].longitud]).addTo(mapa);$('#replay').max=puntos.length-1;$('#replay').oninput=()=>{const p=puntos[+$('#replay').value];marker.setLatLng([p.latitud,p.longitud]);$('#hora').textContent=new Date(p.fecha).toLocaleString('es-AR')+' · precisión '+p.precision_metros+' m';};$('#replay').oninput();}else{$('#replay').max=0;$('#hora').textContent='Sin puntos para esta fecha.';}
 });await $('#cargarrec').onclick();
}


async function inicio(){
 if(usuario?.rol!=='CONDUCTOR'){
  await menuAdministrador();
  return;
 }
 $('#nav').innerHTML='<button id="home">Mis entregas de hoy</button><button id="salir">Cerrar sesión</button>';
 $('#home').onclick=run(inicio);
 $('#salir').onclick=run(async()=>{
  detenerGps();
  await api('/logout',{method:'POST'});
  sessionStorage.removeItem('sec-dist-apk-gps');
  if(window.SECAndroid){
   localStorage.removeItem('vendedorId');
   sessionStorage.removeItem('sec-distribucion-token');
   location.href='salida/login-vendedor.html';
   return;
  }
  login();
 });
 await abrir('App Conductor');
 const titulo=$('#vista h2');
 if(titulo)titulo.textContent='Mis entregas de hoy';
}